// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MemoryGame","status":true,"description":"Mini-gra MEMORY + ŁĄCZENIE SŁÓWEK (system nauki podróżowania)","parameters":{}},
{"name":"EnglishRPG_Fridge","status":true,"description":"EnglishRPG - Fridge System (Grid Ingredients)","parameters":{}},
{"name":"EnglishRPG_Bed","status":true,"description":"EnglishRPG – Bed System (Sleep & Wake Up)","parameters":{}},
{"name":"EnglishRPG_TaskSystem","status":true,"description":"EnglishRPG – Task System (Kids Learning)","parameters":{}},
{"name":"EnglishRPG_Toilet","status":true,"description":"EnglishRPG – Poranna toaleta (misja, marker, fade, dźwięk)","parameters":{}},
{"name":"EnglishRPG_MenuClean","status":true,"description":"EnglishRPG – Uproszczone menu (usuwanie zbędnych opcji)","parameters":{}},
{"name":"EnglishRPG_Wardrobe","status":true,"description":"EnglishRPG – Szafa (ubieranie się do szkoły)","parameters":{}},
{"name":"EnglishRPG_Backpack","status":true,"description":"EnglishRPG – Spakuj plecak (krok po kroku)","parameters":{}},
{"name":"MirrorNPCMovement","status":true,"description":"NPC kopiuje ruch gracza 1:1","parameters":{}},
{"name":"HideStatusGauges","status":true,"description":"Ukrywa HP, MP i TP w menu statusu","parameters":{}}
];
